export const INITIALIZE_CELL_STATE = "INITIALIZE_CELL_STATE";
export const CHANGE_CELL_STATE = "CHANGE_CELL_STATE";
export const INITIALIZE_SNAKE = "INITIALIZE_SNAKE"
export const SET_FOOD_LOCATION = "SET_FOOD_LOCATION"
export const MOVE_SNAKE = "MOVE_SNAKE"
export const INCREASE_SNAKE_LENGTH = "INCREASE_SNAKE_LENGTH"
